apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wonderful-busy-box
  name: wonderful-busy-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wonderful-busy-box
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wonderful-busy-box
    spec:
      containers:
      - image: busybox
        name: busybox
        ports:
        - containerPort: 5701
        resources: {}
status: {}
