apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wonderful-busy-box
  name: wonderful-busy-box
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wonderful-busy-box
  template:
    metadata:
      labels:
        app: wonderful-busy-box
    spec:
      containers:
      - image: busybox
        name: busybox
        ports:
        - containerPort: 5701
