apiVersion: batch/v1
kind: CronJob
metadata:
  name: testjob
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: testjob
    spec:
      template:
        metadata:
        spec:
          containers:
          - image: busybox
            imagePullPolicy: Always
            name: testjob
            command: [ 'sh', '-c', 'echo This is a good day; sleep 3600' ]
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
