apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wonderful-busybox","app.kubernetes.io/instance":"nginx-app"},"name":"wonderful-busybox","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"wonderful-busybox"}},"template":{"metadata":{"labels":{"app":"wonderful-busybox"}},"spec":{"containers":[{"image":"busybox","name":"busybox","ports":[{"containerPort":5701}]}]}}}}
  creationTimestamp: "2022-03-16T12:25:16Z"
  generation: 5
  labels:
    app: wonderful-busybox
    app.kubernetes.io/instance: nginx-app
  name: wonderful-busybox
  namespace: default
  resourceVersion: "101569"
  uid: 466bfd3c-66ef-4633-9cc5-7899c7f4aef3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wonderful-busybox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wonderful-busybox
    spec:
      containers:
      - image: busybox
        imagePullPolicy: Always
        name: busybox
        command: [ 'sh', '-c', 'echo well done; sleep 3600' ]
        ports:
        - containerPort: 5701
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-03-16T12:25:16Z"
    lastUpdateTime: "2022-03-16T12:25:16Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-03-22T07:36:09Z"
    lastUpdateTime: "2022-03-22T07:36:09Z"
    message: ReplicaSet "wonderful-busybox-6bbbc464bf" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 5
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 1
